apiVersion: v1
data:
  accounts.mark: apiKey, login
  admin.enabled: "true"
  application.instanceLabelKey: ""
  configManagementPlugins: ""
  dex.config: |
    connectors:
    - config:
        clientID: system:serviceaccount:openshift-gitops:openshift-gitops-argocd-dex-server
        clientSecret: eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ5NXQ4YUQ3WEVyRVdCOUZiRTNnV0hoc2tLU1Ztam9GeThxUXl4OVJIQUEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJvcGVuc2hpZnQtZ2l0b3BzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im9wZW5zaGlmdC1naXRvcHMtYXJnb2NkLWRleC1zZXJ2ZXItdG9rZW4tNm5uY3MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoib3BlbnNoaWZ0LWdpdG9wcy1hcmdvY2QtZGV4LXNlcnZlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjFjZjMzZTUwLTFiNjctNDU1Ny05Y2JkLTQ5NmMwMGY3OTA4ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpvcGVuc2hpZnQtZ2l0b3BzOm9wZW5zaGlmdC1naXRvcHMtYXJnb2NkLWRleC1zZXJ2ZXIifQ.lKuU3gMKMpZR8O1rC1Pf0P-w8U3KZRZ6ZTVprn-2TM-A_2e-ingakhQOw4z4IxGnOwv_-6gktV2MhDPHq0a22A-39_AvTLhjXINkLluPZt4qcB2Bax60t_fwzqWUTFMfmyn4tRPiyNfJEHx9qlUYK7XnlebM5IEp7RExH7-rmp3PIfyZK6Fw2ByrDKisNGOqX8E9GKRI2L-_pLkB1DM__iU2_AdlawAeb3qMDVRu9YCq4UfRFkIPXuehwYIQ3hjMvy0FAellxN6TTWBjwpy2wfHg-5Bu6O1S9iYe6NnO450QlnwWhxY2XbkhxBlY6wdMFDSaInEJSYBY-8lxNl0RfHCeA-gli4LntCjHhUPsaYiNmAyp_zwPefd7DZd7WLDQySNHeQ_WLS6BspaLhe6n2OjUPI0hIm97qJ6Nxu2bEXeAR7CXQ9mid96pwlGyIG6ostcAlGlMiuBvFjqeD0ZG2nEIqe2Akc27SrhyedIymFCRi-hWrSzTgMN61v0XEYFcKYF-B_S1UeZoU5PS69gMNLf0Z8pLsyrtFvGujJi-pW05vOLoUTX-2elX6imHTgYbjmCtlpAQs-qbUQX77xgZIeu8N7B30DHe_-gjZx7S8cfN_dYYyHn7R9nfXNiaXkAEOXej5Dabel9UcVgjga6elgSJfpukMq3LtQgT25v7oYc
        groups: []
        insecureCA: true
        issuer: https://kubernetes.default.svc
        redirectURI: https://openshift-gitops-server-openshift-gitops.apps.cluster-s6gmd.s6gmd.sandbox1734.opentlc.com/api/dex/callback
      id: openshift
      name: OpenShift
      type: openshift
  ga.anonymizeusers: "false"
  ga.trackingid: ""
  help.chatText: ""
  help.chatUrl: ""
  kustomize.buildOptions: ""
  repositories: ""
  repository.credentials: ""
  resource.exclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  resource.inclusions: ""
  statusbadge.enabled: "false"
  url: https://openshift-gitops-server-openshift-gitops.apps.cluster-s6gmd.s6gmd.sandbox1734.opentlc.com
  users.anonymous.enabled: "false"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-11T10:55:22Z"
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: openshift-gitops
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ArgoCD
    name: openshift-gitops
    uid: ceb5df39-4f23-4ea5-b959-9d1c2679d2f5
  resourceVersion: "85290"
  uid: 5a861e5c-603f-4f11-a1c1-d90f4ac743d0
