apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-pre-prod
  target:
    kind: Deployment
    name: myapp
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 4
  target:
    kind: Deployment
    name: myapp    
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-pre-prod
  target:
    kind: Service
    name: myapp 
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-pre-prod
  target:
    kind: Route
    name: myapp        
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-pre-prod
  target:
    kind: Namespace
    name: myapp-development
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-pre-prod
  target:
    kind: RoleBinding
    name: argocd-admin   
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: myapp-pre-prod
  target:
    kind: RoleBinding
    name: myapp-development 
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-pre-prod
  target:
    kind: RoleBinding
    name: myapp-development    
bases:
- ../base





